import video1 from '../assets/video1.webp';
import destiny2 from '../assets/destiny2.png';

const videoData = [
  {
    title: "Destiny 2: The Final Shape | Launch Trailer",
    views: "1.8M",
    comments: "7k",
    time: "6.05",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Destiny 2",
    category: "Gaming",
  },
  // Add more video objects with relevant data
  {
    title: "Example1",
    views: "500k",
    comments: "3k",
    time: "4.20",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "UI-Design",
  },
  {
    title: "Example Video 3",
    views: "800k",
    comments: "10k",
    time: "5.00",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "Github",
  },
  {
    title: "Example Video 4",
    views: "2M",
    comments: "15k",
    time: "6.30",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "NEWS",
  },
  {
    title: "Example Video 5",
    views: "1.2M",
    comments: "5k",
    time: "3.50",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "Sci-fiction",
  },
  {
    title: "Example Video 6",
    views: "900k",
    comments: "7k",
    time: "4.40",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "Gaming",
  },
  {
    title: "Example Video 7",
    views: "1.5M",
    comments: "10k",
    time: "5.20",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "UI-Design",
  },
  {
    title: "Example Video 8",
    views: "3M",
    comments: "20k",
    time: "6.10",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "Github",
  },
  {
    title: "Example Video 9",
    views: "2.5M",
    comments: "12k",
    time: "7.00",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "NEWS",
  },
  {
    title: "Example Video 10",
    views: "1.1M",
    comments: "4k",
    time: "5.15",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "Sci-fiction",
  },
  {
    title: "Example Video 11",
    views: "2.8M",
    comments: "11k",
    time: "6.25",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "Gaming",
  },
  {
    title: "Example Video 12",
    views: "3.5M",
    comments: "25k",
    time: "7.30",
    imgSrc: video1,
    profileImgSrc: destiny2,
    profileTitle: "Example",
    category: "UI-Design",
  },
];

export default videoData;
